# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Om Prakash Singh
email: omps@omps.in
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - System Administrator - Unix system Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.omps.in" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: ohgnis
github_username:  omps
facebook_username: ompnix
#instagram_username: beyonce
stackoverflow_url: http://stackoverflow.com/users/2210670/omps
googleplus_username: +OmPrakashomps
#skype_username: echo123
linkedin_url: https://in.linkedin.com/in/ompsingh

# Address information
address_street: Central Mumbai
address_city: Thane
address_state: MH
# address_zip:

# Build settings
markdown: kramdown
